// <auto-generated />
using System;
using ComputerAuditServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComputerAuditServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComputerAuditServer.Models.AuditReport", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DomainUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullReportJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasChanges")
                        .HasColumnType("boolean");

                    b.Property<int?>("PreviousReportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WindowsVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreviousReportId");

                    b.ToTable("audit_reports", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.CPUInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<int>("Cores")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Threads")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("cpu_infos", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synced");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("PcId")
                        .HasColumnType("integer")
                        .HasColumnName("pc_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsSynced");

                    b.HasIndex("PcId");

                    b.ToTable("event_log");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.GPUInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AdapterRAMGB")
                        .HasColumnType("double precision");

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<string>("DriverDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PNDeviceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("gpu_infos", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.MonitorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<string>("ConnectionPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DiagonalInches")
                        .HasColumnType("double precision");

                    b.Property<string>("EDIDHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HorizontalSizeCm")
                        .HasColumnType("integer");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManufacturerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VerticalSizeCm")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekOfManufacture")
                        .HasColumnType("integer");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("monitor_infos", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("motherboards", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.NetworkAdapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<string>("IPv4Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("network_adapters", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("office_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfficeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("floor");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.HasKey("OfficeId");

                    b.ToTable("office");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PC", b =>
                {
                    b.Property<int>("IdPc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pc");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPc"));

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("computer_name");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("inventory_number");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("integer")
                        .HasColumnName("office_id");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("os_version");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("processor");

                    b.Property<int>("RamGb")
                        .HasColumnType("integer")
                        .HasColumnName("ram_gb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StorageGb")
                        .HasColumnType("integer")
                        .HasColumnName("storage_gb");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("IdPc");

                    b.HasIndex("ComputerName");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.HasIndex("LastSeen");

                    b.HasIndex("OfficeId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("pc");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PCReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PcId")
                        .HasColumnType("integer")
                        .HasColumnName("pc_id");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("report_status");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.HasKey("Id");

                    b.HasIndex("PcId");

                    b.HasIndex("ReportedAt");

                    b.ToTable("pc_report");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PhysicalDisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SizeGB")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("physical_disks", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PrinterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPrintTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("printer_infos", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.RAMInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<double>("TotalRAMGB")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer");

                    b.Property<int>("UsedSlots")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("ram_infos", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.RAMModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacityGB")
                        .HasColumnType("double precision");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RAMInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("RAMInfoId1")
                        .HasColumnType("integer");

                    b.Property<string>("SpeedMHz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RAMInfoId");

                    b.HasIndex("RAMInfoId1");

                    b.ToTable("ram_modules", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.SystemIdentifiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditReportId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditReportId1")
                        .HasColumnType("integer");

                    b.Property<string>("BIOSSerial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemUUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuditReportId1");

                    b.ToTable("system_identifiers", (string)null);
                });

            modelBuilder.Entity("ComputerAuditServer.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("IdUser");

                    b.ToTable("user");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.AuditReport", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.CPUInfo", "CPU")
                        .WithOne()
                        .HasForeignKey("ComputerAuditServer.Models.AuditReport", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.Motherboard", "Motherboard")
                        .WithOne()
                        .HasForeignKey("ComputerAuditServer.Models.AuditReport", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.RAMInfo", "RAM")
                        .WithOne()
                        .HasForeignKey("ComputerAuditServer.Models.AuditReport", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.SystemIdentifiers", "SystemIds")
                        .WithOne()
                        .HasForeignKey("ComputerAuditServer.Models.AuditReport", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.AuditReport", "PreviousReport")
                        .WithMany()
                        .HasForeignKey("PreviousReportId");

                    b.Navigation("CPU");

                    b.Navigation("Motherboard");

                    b.Navigation("PreviousReport");

                    b.Navigation("RAM");

                    b.Navigation("SystemIds");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.CPUInfo", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.EventLog", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.PC", "PC")
                        .WithMany("EventLogs")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.GPUInfo", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", null)
                        .WithMany("GPUs")
                        .HasForeignKey("AuditReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.MonitorInfo", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", null)
                        .WithMany("Monitors")
                        .HasForeignKey("AuditReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.Motherboard", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.NetworkAdapter", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", null)
                        .WithMany("NetworkAdapters")
                        .HasForeignKey("AuditReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PC", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.Office", "Office")
                        .WithMany("PCs")
                        .HasForeignKey("OfficeId");

                    b.HasOne("ComputerAuditServer.Models.User", "User")
                        .WithMany("PCs")
                        .HasForeignKey("UserId");

                    b.Navigation("Office");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PCReport", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.PC", "PC")
                        .WithMany("PCReports")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PhysicalDisk", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", null)
                        .WithMany("PhysicalDisks")
                        .HasForeignKey("AuditReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PrinterInfo", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", null)
                        .WithMany("Printers")
                        .HasForeignKey("AuditReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.RAMInfo", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.RAMModule", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.RAMInfo", null)
                        .WithMany("Modules")
                        .HasForeignKey("RAMInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerAuditServer.Models.RAMInfo", "RAMInfo")
                        .WithMany()
                        .HasForeignKey("RAMInfoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RAMInfo");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.SystemIdentifiers", b =>
                {
                    b.HasOne("ComputerAuditServer.Models.AuditReport", "AuditReport")
                        .WithMany()
                        .HasForeignKey("AuditReportId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditReport");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.AuditReport", b =>
                {
                    b.Navigation("GPUs");

                    b.Navigation("Monitors");

                    b.Navigation("NetworkAdapters");

                    b.Navigation("PhysicalDisks");

                    b.Navigation("Printers");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.Office", b =>
                {
                    b.Navigation("PCs");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.PC", b =>
                {
                    b.Navigation("EventLogs");

                    b.Navigation("PCReports");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.RAMInfo", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("ComputerAuditServer.Models.User", b =>
                {
                    b.Navigation("PCs");
                });
#pragma warning restore 612, 618
        }
    }
}
